g++ -Iinclude include/Alegengine/src/* -Iinclude/Alegengine/third-party main.cpp -o game \
  -lglfw \
  -lGL \
  -ldl \
  -lpthread \
  -lX11 \
  -lXrandr \
  -lXi \
  -lXxf86vm \
  -lXcursor \
  -lm
